### PR TITLE
Bugfix/skip space after equals

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-standoc#595

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Comment by ronaldtse** [comment]
@CAMOBAP how do we bump release?

**Comment by CAMOBAP** [comment]
@ronaldtse I think make sense to do manual release for this fix, because there is no jar released, I will do

**Comment by ronaldtse** [comment]
Thanks!

**Pull request merged**
